baseURL = "https://dontreboot.me"
languageCode = "en-us"
title = "Patrick O'Connor"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "spof"

[params]
    author = "Patrick O'Connor"
    info = "SRE/Devops"
    description = "Patrick O'Connor's personal website"
    keywords = "blog,developer,personal,devops,sre,cloud,automation"
    avatarurl = "images/oculus.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/dontrebootme/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/dontrebootme/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/dontrebootme/"


# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"

